# Generated by Django 2.0.1 on 2018-03-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20180317_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='inf',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
